@Library("SharedLibrary")_
pipeline
{
    agent any
    stages
    {
        stage("ContinousDownload")
        {
            steps
            {
                script
                {
                    functs.newDownload('maven2')
                }
            }
        }
        stage("ContinousBuilding")
        {
            steps
            {
                script
                {
                    functs.newBuild()
                }
            }
        }
        stage("ContinousDeployment")
        {
            steps
            {
                script
                {
                    functs.newDeployment("ThirdPipeline","172.31.11.125",'testapp99')
                }
            }
        }
        stage("ContinousTesting")
        {
            steps
            {
                script
                {
                    functs.newDownload("FunctionalTesting")
                    functs.newTesting("ThirdPipeline","testing.jar")   
                }
            }
        }
    }
}
